version: '3.8'

services:
  backend:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./utility_consumption.db
    volumes:
      - ../data:/app/data
      - ../models:/app/models
    depends_on:
      - database

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=utility_consumption
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/home/jovyan/work/notebooks
      - ../data:/home/jovyan/work/data
      - ../ml:/home/jovyan/work/ml
    environment:
      - JUPYTER_ENABLE_LAB=yes

volumes:
  postgres_data: 